# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc. router.request_context.host

    FileService\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    FileService\Infrastructure\Controller\Common\ErrorController:
        arguments:
            - '@http_kernel'
            - '@error_renderer'

    file.service.normalizer:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer

    file.service.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - ['@file.service.normalizer']
            - ['@serializer.encoder.json']

    serializer: '@file.service.serializer'

    env.files.path.resolver:
        class: FileService\Application\Service\PathResolver
        autowire: false
        arguments:
            - '%env(FILE_SAVER_PATH)%'
            - '@tmp.path.resolver'

    tmp.path.resolver:
        class: FileService\Application\Service\TempPathResolver
        arguments:
            - '@project.files.path.resolver'

    project.files.path.resolver:
        class: FileService\Application\Service\PathResolver
        arguments:
            - '%kernel.project_dir%/files'

    FileService\Application\Service\FileService:
        lazy: true
        arguments:
            - '@Symfony\Component\Filesystem\Filesystem'
            - '@FileService\Application\Dto\SaveFileDtoFactory'
            - '@file.service.serializer'
            - '@FileService\Application\Dto\DownloadFileDtoFactory'
            - '@env.files.path.resolver'

    FileService\Application\Dto\SaveFileDtoFactory: ~

    FileService\Application\Dto\DownloadFileDtoFactory: ~


